// src/utils/airlineIataCodes.js
export const airlineIataCodes = {
  'Delta Airlines': 'DL',
  'American Airlines': 'AA',
  'United Airlines': 'UA',
  'British Airways': 'BA',
  'Emirates': 'EK',
  'Qatar Airways': 'QR',
  'Singapore Airlines': 'SQ',
  'Lufthansa': 'LH',
  'Air France': 'AF',
  'KLM': 'KL',
  'Japan Airlines': 'JL',
  'ANA': 'NH',
  'Qantas': 'QF',
  'Korean Air': 'KE',
  'Asiana Airlines': 'OZ',
  'Vietnam Airlines': 'VN',
  'Bangkok Airways': 'PG',
  'Hawaiian Airlines': 'HA',
  'Southwest Airlines': 'WN',
  'Alaska Airlines': 'AS',
  'Iberia': 'IB',
  'Saudia': 'SV',
  'EgyptAir': 'MS',
  'Kenya Airways': 'KQ',
  'South African Airways': 'SA',
  'Virgin Atlantic': 'VS',
  'Etihad Airways': 'EY'
};