// src/utils/airlineDomains.js
export const airlineDomains = {
  'Delta Airlines': 'delta.com',
  'American Airlines': 'aa.com',
  'United Airlines': 'united.com',
  'British Airways': 'britishairways.com',
  'Emirates': 'emirates.com',
  'Qatar Airways': 'qatarairways.com',
  'Singapore Airlines': 'singaporeair.com',
  'Lufthansa': 'lufthansa.com',
  'Air France': 'airfrance.com',
  'KLM': 'klm.com',
  'Japan Airlines': 'jal.com',
  'ANA': 'ana.co.jp',
  'Qantas': 'qantas.com',
  'Korean Air': 'koreanair.com',
  'Asiana Airlines': 'flyasiana.com',
  'Vietnam Airlines': 'vietnamairlines.com',
  'Bangkok Airways': 'bangkokair.com',
  'Hawaiian Airlines': 'hawaiianairlines.com',
  'Southwest Airlines': 'southwest.com',
  'Alaska Airlines': 'alaskaair.com',
  'Iberia': 'iberia.com',
  'Saudia': 'saudia.com',
  'EgyptAir': 'egyptair.com',
  'Kenya Airways': 'kenya-airways.com',
  'South African Airways': 'flysaa.com',
  'Virgin Atlantic': 'virginatlantic.com',
  'Etihad Airways': 'etihad.com'
};