// export const flights = [
//   // JFK to LHR (New York to London)
//   {
//     id: 1,
//     airline: "Delta Airlines",
//     flightNumber: "DL452",
//     from: { code: "JFK", city: "New York", terminal: "4" },
//     to: { code: "LHR", city: "London", terminal: "3" },
//     departureDate: "2024-05-15",
//     departureTime: "08:30",
//     arrivalDate: "2024-05-15",
//     arrivalTime: "20:30",
//     duration: "7h 00m",
//     stops: 0,
//     price: 450,
//     cabinClass: "Economy",
//     seats: ["24A", "24B", "24C"],
//     logo: "D"
//   },
//   {
//     id: 2,
//     airline: "Emirates",
//     flightNumber: "EK101",
//     from: { code: "JFK", city: "New York", terminal: "4" },
//     to: { code: "LHR", city: "London", terminal: "3" },
//     departureDate: "2024-05-15",
//     departureTime: "10:00",
//     arrivalDate: "2024-05-15",
//     arrivalTime: "22:00",
//     duration: "7h 15m",
//     stops: 0,
//     price: 520,
//     cabinClass: "Economy",
//     seats: ["12A", "12B"],
//     logo: "E"
//   },
//   {
//     id: 3,
//     airline: "American Airlines",
//     flightNumber: "AA205",
//     from: { code: "JFK", city: "New York", terminal: "4" },
//     to: { code: "LHR", city: "London", terminal: "3" },
//     departureDate: "2024-05-15",
//     departureTime: "12:30",
//     arrivalDate: "2024-05-15",
//     arrivalTime: "23:45",
//     duration: "7h 20m",
//     stops: 1,
//     price: 380,
//     cabinClass: "Economy",
//     seats: ["18A", "18B", "18C"],
//     logo: "A"
//   },
//   {
//     id: 4,
//     airline: "United Airlines",
//     flightNumber: "UA876",
//     from: { code: "JFK", city: "New York", terminal: "4" },
//     to: { code: "LHR", city: "London", terminal: "3" },
//     departureDate: "2024-05-15",
//     departureTime: "14:00",
//     arrivalDate: "2024-05-16",
//     arrivalTime: "01:30",
//     duration: "8h 00m",
//     stops: 1,
//     price: 410,
//     cabinClass: "Economy",
//     seats: ["15A", "15B"],
//     logo: "U"
//   },
//   {
//     id: 5,
//     airline: "British Airways",
//     flightNumber: "BA112",
//     from: { code: "JFK", city: "New York", terminal: "4" },
//     to: { code: "LHR", city: "London", terminal: "3" },
//     departureDate: "2024-05-15",
//     departureTime: "15:45",
//     arrivalDate: "2024-05-16",
//     arrivalTime: "03:15",
//     duration: "7h 45m",
//     stops: 0,
//     price: 490,
//     cabinClass: "Business",
//     seats: ["2A", "2B"],
//     logo: "B"
//   },
//   {
//     id: 6,
//     airline: "Delta Airlines",
//     flightNumber: "DL500",
//     from: { code: "JFK", city: "New York", terminal: "4" },
//     to: { code: "LHR", city: "London", terminal: "3" },
//     departureDate: "2024-05-15",
//     departureTime: "18:00",
//     arrivalDate: "2024-05-16",
//     arrivalTime: "05:30",
//     duration: "7h 30m",
//     stops: 0,
//     price: 550,
//     cabinClass: "Premium Economy",
//     seats: ["8A", "8B", "8C"],
//     logo: "D"
//   },
//   // CDG to NRT (Paris to Tokyo)
//   {
//     id: 7,
//     airline: "Air France",
//     flightNumber: "AF275",
//     from: { code: "CDG", city: "Paris", terminal: "2" },
//     to: { code: "NRT", city: "Tokyo", terminal: "1" },
//     departureDate: "2024-05-15",
//     departureTime: "11:00",
//     arrivalDate: "2024-05-16",
//     arrivalTime: "08:00",
//     duration: "11h 30m",
//     stops: 0,
//     price: 650,
//     cabinClass: "Economy",
//     seats: ["32A", "32B"],
//     logo: "AF"
//   },
//   {
//     id: 8,
//     airline: "Japan Airlines",
//     flightNumber: "JL007",
//     from: { code: "CDG", city: "Paris", terminal: "2" },
//     to: { code: "NRT", city: "Tokyo", terminal: "1" },
//     departureDate: "2024-05-15",
//     departureTime: "13:30",
//     arrivalDate: "2024-05-16",
//     arrivalTime: "10:00",
//     duration: "11h 45m",
//     stops: 0,
//     price: 720,
//     cabinClass: "Economy",
//     seats: ["18A", "18B", "18C"],
//     logo: "JL"
//   },
//   // LAX to SFO (Los Angeles to San Francisco)
//   {
//     id: 9,
//     airline: "United Airlines",
//     flightNumber: "UA1234",
//     from: { code: "LAX", city: "Los Angeles", terminal: "7" },
//     to: { code: "SFO", city: "San Francisco", terminal: "3" },
//     departureDate: "2024-05-15",
//     departureTime: "09:00",
//     arrivalDate: "2024-05-15",
//     arrivalTime: "10:30",
//     duration: "1h 15m",
//     stops: 0,
//     price: 150,
//     cabinClass: "Economy",
//     seats: ["12A", "12B", "12C"],
//     logo: "U"
//   },
//   {
//     id: 10,
//     airline: "Southwest Airlines",
//     flightNumber: "SW456",
//     from: { code: "LAX", city: "Los Angeles", terminal: "1" },
//     to: { code: "SFO", city: "San Francisco", terminal: "2" },
//     departureDate: "2024-05-15",
//     departureTime: "15:00",
//     arrivalDate: "2024-05-15",
//     arrivalTime: "16:20",
//     duration: "1h 20m",
//     stops: 0,
//     price: 120,
//     cabinClass: "Economy",
//     seats: ["25A", "25B"],
//     logo: "SW"
//   },
//   // DXB to SYD (Dubai to Sydney)
//   {
//     id: 11,
//     airline: "Emirates",
//     flightNumber: "EK405",
//     from: { code: "DXB", city: "Dubai", terminal: "1" },
//     to: { code: "SYD", city: "Sydney", terminal: "1" },
//     departureDate: "2024-05-15",
//     departureTime: "14:00",
//     arrivalDate: "2024-05-17",
//     arrivalTime: "05:45",
//     duration: "14h 30m",
//     stops: 0,
//     price: 850,
//     cabinClass: "Economy",
//     seats: ["45A", "45B"],
//     logo: "E"
//   },
//   {
//     id: 12,
//     airline: "Qantas",
//     flightNumber: "QF16",
//     from: { code: "DXB", city: "Dubai", terminal: "3" },
//     to: { code: "SYD", city: "Sydney", terminal: "1" },
//     departureDate: "2024-05-15",
//     departureTime: "11:30",
//     arrivalDate: "2024-05-17",
//     arrivalTime: "06:00",
//     duration: "15h 00m",
//     stops: 1,
//     price: 780,
//     cabinClass: "Economy",
//     seats: ["22A", "22B", "22C"],
//     logo: "QF"
//   },
// ];

export const bookings = [
  {
    reference: "ABC123",
    email: "john@example.com",
    passenger: { name: "John Smith", dob: "1985-05-15", passport: "AB123456" },
    // flights: [flights[0]],
    totalPaid: 595.50,
    status: "confirmed"
  },
  {
    reference: "XYZ789",
    email: "jane@example.com",
    passenger: { name: "Jane Doe", dob: "1990-08-22", passport: "CD789012" },
    // flights: [flights[2]],
    totalPaid: 489.25,
    status: "confirmed"
  }
];

export const popularDestinations = [
  { from: "New York", to: "London", price: 450 },
  { from: "Paris", to: "Tokyo", price: 820 },
  { from: "Dubai", to: "Sydney", price: 980 },
  { from: "Los Angeles", to: "Cancun", price: 320 }
];
